FROM node:18 as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

FROM node:18.15.0-bullseye
RUN apt-get update && apt-get install -y inetutils-ping
WORKDIR /usr/src/app
ARG NODE_ENV
ARG REACT_APP_BACKEND_PORT
ENV NODE_ENV ${NODE_ENV}
ENV REACT_APP_BACKEND_PORT ${REACT_APP_BACKEND_PORT}
COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
USER node
