services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend

    volumes:
      - ./backend:/usr/src/app

    environment:
      - NODE_ENV=development
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

    command: ["npm", "run", "dev"]
